#pragma once

enum TEXTYPE	{ TEX_SINGLE, TEX_MULTI, TEX_END };

enum  OBJID     {  OBJ_TERRAIN, OBJ_PLAYER, OBJ_BULLET, OBJ_UI, OBJ_END };

enum CHANNELID { SOUND_EFFECT, SOUND_BGM, SOUND_PLAYER, SOUND_MONSTER,  MAXCHANNEL };